### PR TITLE
new tags added

### PR DESCRIPTION
**Pull request by Zeeshandotconsole**

### CODE REVIEW

**Comment by Zeeshandotconsole** [comment]
I want the changes in codes.

**Review by Zeeshandotconsole — COMMENTED** [review]
I want that you remove the h2 and below p tag.

**Review by MuhammadZeeshan56 — COMMENTED** [review]
Sure. I'll make changes and will update the file.

**Comment by Zeeshandotconsole** [comment]
Ok, first remove those mentioned tags and then add a description paragraph about that file.

**Comment by MuhammadZeeshan56** [comment]
Sure, I'll do accordingly.

**Pull request merged**
